# Convert Masternode Rewards
trigger: "balance > 10"
action:
  - swap:
      symbol: USDC
      address: 0x23b9...
      percentage: 25
  - swap:
      symbol: TUSD
      address: 0x15cff...
      percentage: 50
  - transfer:
      address: XuHMg...
      percentage: 25
